# Generated by Django 5.0.6 on 2024-06-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chercheur',
            name='projets',
            field=models.ManyToManyField(blank=True, related_name='chercheurs', to='core.projetderecherche'),
        ),
    ]
